name: 'Promote'
description: 'Promotes the code to a Kubernetes environment'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.name }}
inputs:
  github_container_registry_token:
    description: 'A GitHub Personal Access Token with `write:packages` scope'
    required: true
  name:
    description: 'Name of the App (eg. Broadband Plans)'
    required: true
