name: 'Promote'
description: 'Promotes the code to a Kubernetes environment'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.name }}
    - ${{ inputs.namespace }}
    - ${{ inputs.overlay }}
inputs:
  name:
    description: 'Name of the app (eg. Broadband Plans)'
    required: true
  namespace:
    description: 'Kubernetes namespace to deploy to'
    required: true
  overlay:
    description: 'Kustomize overlay to apply (eg. staging, production)'
    required: true
  github_container_registry_token:
    description: 'A GitHub Personal Access Token with `write:packages` scope'
    required: true
