name: 'Promote'
description: 'Promotes the code to a Kubernetes environment'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.environment }}
inputs:
  deployment_statuses_url:
    description: 'URL where deployment statuses can be created'
    required: true
  deployment_pull_request_url:
    description: "URL for Pull Request which triggered this deployment"
    required: false
  environment:
    description: "Environment to deploy to either 'production' or 'staging/$NAMESPACE'"
    required: true
  github_access_token:
    description: 'A GitHub Personal Access Token with `repo`, and `write:packages` scope'
    required: true
