#!/usr/bin/env bash

set -eo pipefail
set -x

################################################################################
# AWS
################################################################################
pip3 install --break-system-packages awscli


################################################################################
# Yq
################################################################################
curl -s https://api.github.com/repos/mikefarah/yq/releases/latest |\
    jq -r '.assets[].browser_download_url' |\
    grep yq_linux_amd64 |\
    xargs curl -O -L
chmod +x yq_linux_amd64
mv yq_linux_amd64 /usr/local/bin/yq


################################################################################
# Kubectl
################################################################################
curl -o /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.18.5/bin/linux/amd64/kubectl
chmod +x /usr/local/bin/kubectl


################################################################################
# Kustomize
################################################################################
curl -s https://api.github.com/repos/kubernetes-sigs/kustomize/releases/tags/kustomize/v4.1.2 |\
    jq -r '.assets[].browser_download_url' |\
    grep linux_amd64 |\
    xargs curl -o kustomize.tar.gz -L
tar -xzvf "kustomize.tar.gz"
chmod +x kustomize
mv kustomize /usr/local/bin/kustomize
rm kustomize.tar.gz
