apiVersion: builtin
kind: LabelTransformer
metadata:
  name: DeploymentLabeller
labels:
  switcher.ie/app: $APP
  switcher.ie/sha: $GITHUB_SHA
fieldSpecs:
- path: metadata/labels
  create: true
  kind: Deployment
---
apiVersion: builtin
kind: AnnotationsTransformer
metadata:
  name: DeploymentLabeller
annotations:
fieldSpecs:
- path: metadata/annotations
  create: true
  kind: Deployment
