#!/usr/bin/env bash

################################################################################
# Set Variables
################################################################################
NAME="$1"
TAG="$2"
GIT_SHA="$3"
NAMESPACE="$4"
ENVIRONMENT="$5"

echo "NAME is $NAME"
echo "TAG is $TAG"
echo "GIT_SHA is $GIT_SHA"
echo "NAMESPACE is $NAMESPACE"
echo "ENVIRONMENT is $ENVIRONMENT"

# Build Image

/bin/build "${TAG}" "${GIT_SHA}"

# # # Push Image

# /bin/build/push "${{ steps.tag.outputs.tag }}"

# # # Promote

# /bin/build/promote "${{ steps.namespace.outputs.namespace }}" "staging" "${{ steps.tag.outputs.tag }}"

# # # Notify Slack

# /bin/build/slack "${{ secrets.SLACK_WEBHOOK }}" "development" "Vertical Products" "$GITHUB_SHA" "https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA" "${{ steps.tag.outputs.tag }}" "${{ steps.namespace.outputs.namespace }}"
