#!/usr/bin/env bash

set -eo pipefail

################################################################################
# Validate Inputs
################################################################################

function usage {
    echo "usage: $0 [webhook] [channel] [app] [sha]"
    echo "  name         name of the app (eg. Broadband Plans)"
    echo "  namespace    Kuberenetes namespace to deploy to (eg. fuchsia)"
    echo "  overlay      Kubstomize overlay to apply (eg. staging...)"
    exit 1
}

[ -z "$3" ] && { usage; }

################################################################################
# Set Inputs
################################################################################

NAME="$1"
NAMESPACE="$2"
OVERLAY="$3"

################################################################################
# Set Variables
################################################################################

TAG="${GITHUB_SHA::7}"
APP="${GITHUB_REPOSITORY/switcher-ie\//}"

################################################################################
# Set Path
################################################################################

export PATH="$PATH:/bin"

################################################################################
# Setup Failed Deployment Handler
################################################################################

failed_deployment() {
  update-deployment-status "$APP" "$OVERLAY" "$NAMESPACE" "$INPUT_DEPLOYMENT_STATUSES_URL" 'failure'
}

trap 'failed_deployment' ERR

################################################################################
# Update Deployment Status (In Progress)
################################################################################

update-deployment-status "$APP" "$OVERLAY" "$NAMESPACE" "$INPUT_DEPLOYMENT_STATUSES_URL" 'in_progress'

################################################################################
# Login to GitHub Container Registry
################################################################################

echo "$INPUT_GITHUB_ACCESS_TOKEN" | docker login ghcr.io -u switcher-ie-deploy --password-stdin

################################################################################
# Login to ECR
################################################################################

$(aws ecr get-login --no-include-email)

################################################################################
# Promote
################################################################################

promote "${NAMESPACE}" "${OVERLAY}" "${TAG}" "${APP}"

################################################################################
# Update Deployment Status (Success)
################################################################################

update-deployment-status "$APP" "$OVERLAY" "$NAMESPACE" "$INPUT_DEPLOYMENT_STATUSES_URL" 'success'
