#!/usr/bin/env bash

set -eo pipefail

################################################################################
# Validate Inputs
################################################################################

function usage {
    echo "usage: $0 [environment]"
    echo "  environment  either 'production' or 'staging/\$NAMESPACE'"
    exit 1
}

[ -z "$1" ] && { usage; }

################################################################################
# Set Inputs
################################################################################

DEPLOYMENT_ENVIRONMENT="$1"

ENVIRONMENT=$(echo "$DEPLOYMENT_ENVIRONMENT" | cut -d/ -f1)
NAMESPACE=$(echo "$DEPLOYMENT_ENVIRONMENT" | cut -d/ -f2)

################################################################################
# Set Variables
################################################################################

TAG="${GITHUB_SHA::7}"
APP="${GITHUB_REPOSITORY/switcher-ie\//}"

################################################################################
# Set Path
################################################################################

export PATH="$PATH:/bin"

################################################################################
# Setup Failed Deployment Handler
################################################################################

failed_deployment() {
  update-deployment-status "$APP" "$ENVIRONMENT" "$NAMESPACE" "$INPUT_DEPLOYMENT_STATUSES_URL" 'failure'
}

trap 'failed_deployment' ERR

################################################################################
# Update Deployment Status (In Progress)
################################################################################

update-deployment-status "$APP" "$ENVIRONMENT" "$NAMESPACE" "$INPUT_DEPLOYMENT_STATUSES_URL" 'in_progress'

################################################################################
# Login to GitHub Container Registry
################################################################################

echo "$INPUT_GITHUB_ACCESS_TOKEN" | docker login ghcr.io -u switcher-ie-deploy --password-stdin

################################################################################
# Login to ECR
################################################################################

aws ecr get-login-password | docker login --username AWS --password-stdin "$ECR_ENDPOINT"

################################################################################
# Promote
################################################################################

promote "${NAMESPACE}" "${ENVIRONMENT}" "${TAG}" "${APP}"

################################################################################
# Update Deployment Status (Success)
################################################################################

update-deployment-status "$APP" "$ENVIRONMENT" "$NAMESPACE" "$INPUT_DEPLOYMENT_STATUSES_URL" 'success'
