#!/usr/bin/env bash

################################################################################
# Set Variables
################################################################################
NAME="$1"
NAMESPACE="$2"
ENVIRONMENT="$3"
SLACK_WEBHOOK="$4"

TAG="${GITHUB_SHA::7}"
GIT_SHA="${GITHUB_SHA}"
APP="${GITHUB_REPOSITORY/switcher-ie\//}"

export ENDPOINT="285532152610.dkr.ecr.eu-west-1.amazonaws.com"
export CLUSTER="switcher"

echo "NAME is $NAME"
echo "TAG is $TAG"
echo "GIT_SHA is $GIT_SHA"
echo "NAMESPACE is $NAMESPACE"
echo "ENVIRONMENT is $ENVIRONMENT"
echo "APP is $APP"
echo "GITHUB_WORKSPACE is $GITHUB_WORKSPACE"
echo "SLACK_WEBHOOK is $SLACK_WEBHOOK"

export PATH="$PATH:/deploy"

# Build Image

build "${TAG}" "${GIT_SHA}" "${APP}"

# Push Image

push "${TAG}" "${APP}"

# Promote

promote "${NAMESPACE}" "${ENVIRONMENT}" "${TAG}" "${APP}"

# Notify Slack

slack "${SLACK_WEBHOOK}" "development" "${NAME}" "$GIT_SHA" "https://github.com/$GITHUB_REPOSITORY/commit/$GIT_SHA" "${TAG}" "${NAMESPACE}"
