#!/usr/bin/env bash

set -eo pipefail

################################################################################
# Validate Inputs
################################################################################

function usage {
    echo "usage: $0 [namespace] [tag]"
    echo "  namespace    namespace to promote the image (eg. production)"
    echo "  tag          tag of the image version (eg. latest)"
    echo "  app          slug of the app (eg. broadband-plans)"
    exit 1
}

[ -z "$1" ] && { usage; }

################################################################################
# Set Inputs
################################################################################

NAMESPACE=$1
TAG=$2
APP=$3

################################################################################
# Constants
################################################################################

DIR="$(dirname "${BASH_SOURCE[0]}")"

################################################################################
# Setup Environment
################################################################################

source ${DIR}/../env

################################################################################
# Set Variables
################################################################################

REPOSITORY="$ENDPOINT/$APP"

################################################################################
# Set migration properties
################################################################################

pushd k8s/pre-release
$debug kustomize edit set image unset=$REPOSITORY:$TAG
popd

################################################################################
# Cleanup old migration jobs
################################################################################

if kubectl get jobs -n $NAMESPACE | grep -q $APP-migration; then
  $debug kubectl delete job/$APP-migration -n $NAMESPACE
fi

################################################################################
# Run migration
################################################################################

$debug kubectl apply -k k8s/pre-release -n $NAMESPACE
$debug kubectl wait --for=condition=complete job/$APP-migration --timeout=15m -n $NAMESPACE

################################################################################
# Cleanup migration job
################################################################################
$debug kubectl delete job/$APP-migration -n $NAMESPACE
