#!/usr/bin/env bash

set -eo pipefail

################################################################################
# Validate Inputs
################################################################################

function usage {
    echo "usage: $0 [namespace]"
    echo "  namespace    namespace to publish assets to (eg. production)"
    exit 1
}

[ -z "$1" ] && { usage; }

################################################################################
# Set Inputs
################################################################################

NAMESPACE=$1

################################################################################
# Set Variables
################################################################################

BUCKET_NAME="switcher-$NAMESPACE-cms-assets"

pwd
ls
cd public
ls

################################################################################
# Publish Assets to S3
################################################################################

aws s3 cp --recursive --cache-control "public, max-age=31536000" "$GITHUB_WORKSPACE/public/assets" "s3://$BUCKET_NAME/assets"
aws s3 cp --recursive --cache-control "public, max-age=31536000" "$GITHUB_WORKSPACE/public/packs" "s3://$BUCKET_NAME/packs"
