#!/usr/bin/env bash

set -eo pipefail

################################################################################
# Validate Inputs
################################################################################

function usage {
    echo "usage: $0 [api_key] [build] [username] [repository] [revision] [environment]"
    echo "  api_key       Bugsnag Api Key (eg. A72101d77904c7ce...)"
    echo "  build         Build version being deployed (eg. 55197c6)"
    echo "  username      User that instigated the deploy (eg. carlgaywood)"
    echo "  repository    GitHub repository of the app (eg. https://github.com/switcher/...)"
    echo "  revision      Git revision being built (eg. 45da59defecaaa7c9fc...)"
    echo "  environment   Environment being deployed to (eg. production)"
    exit 1
}

[ -z "$1" ] && { usage; }

################################################################################
# Set Inputs
################################################################################

API_KEY=$1
BUILD=$2
USERNAME=$3
REPOSITORY=$4
REVISION=$5
ENVIRONMENT=$6

################################################################################
# Constants
################################################################################

DIR="$(dirname "${BASH_SOURCE[0]}")"

################################################################################
# Post to Bugsnag
################################################################################

curl https://build.bugsnag.com/ \
  --header "Content-Type: application/json" \
  --data "{
    \"apiKey\": \"$API_KEY\",
    \"appVersion\": \"$BUILD\",
    \"releaseStage\": \"$ENVIRONMENT\",
    \"builderName\": \"$USERNAME\",
    \"sourceControl\": {
      \"provider\": \"github\",
      \"repository\": \"$REPOSITORY\",
      \"revision\": \"$REVISION\"
    },
    \"metadata\": {}
  }"
