#!/usr/bin/env bash

set -eo pipefail

################################################################################
# Validate Inputs
################################################################################

function usage {
    echo "usage: $0 [tag] [git_sha] [repository]"
    echo "  tag         tag of the image version (eg. latest)"
    echo "  git_sha     sha of the git commit (eg. sd89a7dasd798asd7...)"
    echo "  repository  ECR build repository (eg. broadband-plans)"
    exit 1
}

[ -z "$3" ] && { usage; }

################################################################################
# Set Inputs
################################################################################

TAG=$1
GIT_SHA=$2
REPOSITORY=$3

################################################################################
# Set Variables
################################################################################

IMAGE="$ECR_ENDPOINT/$REPOSITORY:$TAG"

################################################################################
# Build Image
################################################################################

docker build -t "$IMAGE.build" \
  --build-arg GIT_SHA="$GIT_SHA" \
  --build-arg VERSION="$TAG" .
