#!/usr/bin/env bash

set -eo pipefail

################################################################################
# Validate Inputs
################################################################################

function usage {
    echo "usage: $0 [webhook] [channel] [app] [sha] [commit_url] [build] [namespace]"
    echo "  webhook       webhook to post at (eg. https://hooks.slack.com/services/T0DNQ...)"
    echo "  channel       channel to post at (eg. dev_testing)"
    echo "  app           app being released (eg. cms)"
    echo "  sha           sha of the git commit (eg. 07af6000d5a0a40da590d8...)"
    echo "  commit_url    commit url of the deployment (eg. https://github.com/switcher-ie/...)"
    echo "  build         docker build promoted (eg. 364f841)"
    echo "  namespace     namespace deployed to (eg. staging)"
    exit 1
}

[ -z "$1" ] && { usage; }

################################################################################
# Set Inputs
################################################################################

WEBHOOK=$1
CHANNEL=$2
APP=$3
SHA=$4
COMMIT=$5
BUILD=$6
NAMESPACE=$7

################################################################################
# Set Variables
################################################################################

MESSAGE="$(git show-branch --no-name $SHA)"
FALLBACK="Promoted *$APP* <$COMMIT|$MESSAGE> to <https://k8s.switcher.ie/#!/overview?namespace=$NAMESPACE|$NAMESPACE>"
TIMESTAMP=$(date +%s)

################################################################################
# Post to Slack
################################################################################

curl -X POST --data "{
    \"channel\": \"#$CHANNEL\",
    \"attachments\": [
        {
            \"fallback\": \"$FALLBACK\",
            \"color\": \"#36a64f\",
            \"pretext\": \"Promoted build \`$BUILD\`\",
            \"author_name\": \"$APP\",
            \"title\": \"$MESSAGE\",
            \"title_link\": \"$COMMIT/\",
            \"footer\": \"$NAMESPACE\",
            \"ts\": $TIMESTAMP
        }
    ]
}" $WEBHOOK
