#!/usr/bin/env bash

set -eo pipefail

################################################################################
# Validate Inputs
################################################################################

function usage {
    echo "usage: $0 [namespace]"
    echo "  namespace    namespace to promote the image (eg. production)"
    exit 1
}

[ -z "$1" ] && { usage; }

################################################################################
# Set Inputs
################################################################################

NAMESPACE=$1

################################################################################
# Wait for each rollout
################################################################################

for config in k8s/base/deployments/*.yaml; do
  deployment=$(yq r $config metadata.name)
  kubectl rollout status deployment/$deployment -n $NAMESPACE
done
